In [1]:
from datasets import load_dataset
import pandas as pd
import os

In [2]:
import os
from dotenv import load_dotenv

load_dotenv()

hf_token = os.getenv("HF_TOKEN")

if hf_token:
    print("Connexion Hugging Face sécurisée et configurée !")
else:
    print("Erreur : Le token n'a pas été trouvé dans le fichier .env")

Connexion Hugging Face sécurisée et configurée !

In [4]:
ds = load_dataset("cyberec/Prompt-injection-dataset", "core")
print(ds)

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'category', 'source', 'severity', 'group_id', 'augmented', 'tags'],
        num_rows: 4391
    })
    validation: Dataset({
        features: ['text', 'label', 'category', 'source', 'severity', 'group_id', 'augmented', 'tags'],
        num_rows: 941
    })
    test: Dataset({
        features: ['text', 'label', 'category', 'source', 'severity', 'group_id', 'augmented', 'tags'],
        num_rows: 942
    })
})

In [5]:
df_train = ds["train"].to_pandas()
df_val   = ds["validation"].to_pandas()
df_test  = ds["test"].to_pandas()

print("Train :",      len(df_train))   # 4391
print("Validation :", len(df_val))     # 941
print("Test :",       len(df_test))    # 942

Train : 4391
Validation : 941
Test : 942

In [6]:
# Voir les premières lignes
df_train.head()

,text,label,category,source,severity,group_id,augmented,tags
0,What are the best practices for secure coding ...,0,benign,original,,grp_578f04597482,False,"[coding, security_adjacent, hard_negative]"
1,Can you help me write a Python script that fil...,0,benign,original,,grp_b19fdee3675d,False,"[coding, input_filtering, hard_negative]"
2,What does 'prompt engineering' mean?,0,benign,original,,grp_f964158df1fa,False,"[ai_terminology, hard_negative]"
3,Execute the deployment script and push the cha...,0,benign,original,,grp_1a3f1bc3938d,False,"[devops, hard_negative, contains_execute]"
4,Please bypass the cache and fetch fresh data f...,0,benign,original,,grp_d622368f6ce5,False,"[api, hard_negative, contains_bypass]"

In [7]:
# Vérifier les colonnes et types
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 4391 entries, 0 to 4390
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       4391 non-null   str
 1   label      4391 non-null   int32
 2   category   4391 non-null   str
 3   source     4391 non-null   str
 4   severity   4391 non-null   str
 5   group_id   4391 non-null   str
 6   augmented  4391 non-null   bool
 7   tags       4391 non-null   object
dtypes: bool(1), int32(1), object(1), str(5)
memory usage: 1.1+ MB

In [8]:
# Vérifier les valeurs manquantes
df_train.isnull().sum()

text         0
label        0
category     0
source       0
severity     0
group_id     0
augmented    0
tags         0
dtype: int64

In [9]:
# Voir la répartition des labels
print(df_train["label"].value_counts())
# 0 = bénin   (prompt normal)
# 1 = malicieux (prompt injection)

print(df_train["category"].value_counts())
print(df_train["severity"].value_counts())

label
1    2650
0    1741
Name: count, dtype: int64
category
benign                   1699
direct_injection         1397
adversarial               383
jailbreak                 291
encoding                  177
training_extraction        68
edge_case                  42
system_manipulation        29
token_smuggling            27
rag_poisoning              26
persona_replacement        25
agent_manipulation         25
instruction_override       21
control                    17
prompt_injection           16
context_confusion          16
model_fingerprinting       16
output_manipulation        16
prompt_extraction          14
response_manipulation      13
multi_turn                 12
system_extraction          10
payload_injection          10
crescendo                   9
indirect_injection          8
encoding_obfuscation        6
many_shot                   5
code_execution              4
token_injection             4
prompt_leak                 3
chain_of_thought            2
Name: count, dtype: int64
severity
            1741
medium      1631
high         898
critical      95
low           26
Name: count, dtype: int64

In [10]:
# Créer le dossier data/ s'il n'existe pas
os.makedirs("../data", exist_ok=True)

# Sauvegarder les 3 splits
df_train.to_csv("../data/train.csv", index=False)
df_val.to_csv("../data/val.csv",     index=False)
df_test.to_csv("../data/test.csv",   index=False)

print("✅ CSV sauvegardés dans data/")

✅ CSV sauvegardés dans data/

In [11]:
# Recharger depuis CSV pour confirmer
df_check = pd.read_csv("../data/train.csv")

print("Lignes :", len(df_check))                    # 4391
print("Colonnes :", df_check.columns.tolist())      # 5 colonnes
df_check.head(3)

Lignes : 4391
Colonnes : ['text', 'label', 'category', 'source', 'severity', 'group_id', 'augmented', 'tags']

,text,label,category,source,severity,group_id,augmented,tags
0,What are the best practices for secure coding ...,0,benign,original,NaN,grp_578f04597482,False,['coding' 'security_adjacent' 'hard_negative']
1,Can you help me write a Python script that fil...,0,benign,original,NaN,grp_b19fdee3675d,False,['coding' 'input_filtering' 'hard_negative']
2,What does 'prompt engineering' mean?,0,benign,original,NaN,grp_f964158df1fa,False,['ai_terminology' 'hard_negative']